---
journal: jacsat
type: article
author:
  - name: 蓝海
    altaff: "我们认真科学分析复杂金融现象背后的规律"
    email: \email{lh_loki@163.com}
    phone: 13127900572
  - name: 彭莉
   
title:
  formatted: 丘栋荣简评\footnote{详尽的数据分析与记录请联系作者索取《基金管理人分析技术文档》}
  short: 丘栋荣

keywords: 价值投资, PB-ROE
abstract: |
  丘栋荣是最近高光的基金管理人，虽然从业时间不是特别长，但是在2014年至今的牛熊装换的市场中交出了亮眼的成绩，收益年度平均夏普率高达1.43。

  基于公开信息分析，我们认为丘栋荣是典型的价值投资者，其具备超强的选股策略和稳健的择时能力，长期保持低换手率和偏稳健的主动策略，持续的投资于低PB、低PE的中大盘价值股，在过去的价值投资回归过程中取得了亮眼的成绩。
  只要市场维持当前风格，则其表现有望持续。但是，他应对市场风格转换的能力，未能得到市场的持续验证；从其教育背景与工作经历中也没有足够让我们对于这一情况做出乐观评估的依据。倾向于归集他为单一但是强健的价值投资者。

bibliography: acstest.bib
output: rticles::fund_review
---

    
```{r, echo=FALSE, message=FALSE, warning=FALSE, render=TRUE,fig.width=11,results='asis'}
require(CAsset)
require(PerformanceAnalytics)
init()
pdf.options(family = "GB1")
funds=getFunds(codes=c('540006','000849'),fund.names=c('大盘','双核'),from='2009-01-01')
data(asset_top_daily)
hs300<-asset_top_daily[,'stock']
colnames(hs300)<-'沪深300'
funds = merge(funds,hs300,join='left')
#charts.PerformanceSummary(funds,event.labels=c('管理基金'),event.lines=c('2014-09-16'))

knitr::kable(fund.performance(funds),digits=2,col.names=c('名称','近半年','夏普率','近一年','夏普率','近两年','夏普率','近三年','夏普率'))
```


# 简介

  丘栋荣本科毕业于天津大学化学工程与工艺专业，毕业后在有短暂的工程师和食品行业销售的经验。从台资券商群益国际控股消费品行业研究员入行，3年后（2010年）转入汇丰晋信基金管理公司至今，从研究员、高级研究员一直到基金经理，目前管理基金规模125亿元左右，占公司总规模的40%。2013年，丘栋荣接受了长江商学院金融MBA的课程训练。


# 风格评述

基于公开数据，我们使用Sharpe风格分析方法结合自创的主动性风格指标，对于丘栋荣的风格进行了数量分析。结论为：
\begin{itemize}
\item 交易风格：以低换手率,长期地相对集中地投资于低 PB 和低 PE 的股
票来获取收益的。因此该基金在市场风格相对单一、投资者风险偏好较低的
时候具备良好的表现。
\item 持仓风格：偏向价值型股票,尤其以其投资期间估值偏低
的大盘、中盘价值为主。成长型的股票,基本局限在估值尚且合理的大盘成
长型股票。
\item 主动性风格：从接手前的主动风格指数\footnote{主动风格指数为自有指数，数值越大表明基金投资越偏离其参照的被动指数，即显示了更多的主动投资。但是市场毕竟在某种程度上是弱有效的，因此主动指数并非越大越强！}36.7\%，到接
管后的18.3\%，甚至低于行业平均26.8\%，丘栋荣表现有“克制的主动管理”。
\end{itemize}

因此，我们推断丘栋荣为稳健的、严守投资信仰的价值投资者。

# 能力评价\footnote{运气能够带来超常表现，持续的好运则可以归结为能力}

我们将持续的超额表现归因为:
\begin{equation}
\mbox{大类资产配置能力} + \mbox{行业配置能力（股票类）}+ \mbox{择股能力} + \mbox{择时能力} \Rightarrow \mbox{收益} \nonumber
\end{equation}

\begin{table}
  \begin{tabular}{l|llll}
    因子 &大类资产配置  & 行业配置  & 择股能力 & 择时能力  \\ \hline
    贡献收益 & $0.56\%$   & $-1.28\%$ & $18.42\%$ &  $20.76\%$  \\
    评价 & 弱 & 无 & 超强 & 强健  \\ \hline
  \end{tabular}
\end{table}

显然，丘栋荣具备良好的择股与择时能力，但是没有表现出大类资产配置、甚至行业配置的能力。这似乎与他的教育经历与从业经验有关。

# 投资策略简述

丘栋荣基本信仰: 成长具备不确定性，收益往往与风险匹配，但是风险并不一定带来收益。寻找市场估值溢价与企业资产盈利能
力的不匹配关系中有益于投资者的方向——价值型股票——作为投资的方向。

具体可以概况为：

\begin{itemize}
\item 基于PB-ROE和基本面结合选股、并且随着PB-ROE关系的变化择时，以往业绩的深度分析，我们证实该方法对于当前的市场风格十分有效。
\item 基于风险溢价的资产配置方法：即将风险溢价水平与历史情况相比较，判断市场是否整体高估或者低估，进而进行资产配置。我们进行的数据分析显示该方法未能贡献明显的收益，但是考虑到过去市场波云诡谲的变化，这种不贡献似乎也是一种“贡献”吧。
\item 基于业绩归因与风险归因的风控方法：即对于投资组合的风险暴露有相应的规划，虽然不是严格的数量控制或者类似桥水的风险平价方法，但是总体上强调“明确赚什么的钱”这样的思路，比起蒙上眼裸奔要好不少。
\end{itemize}

\begin{acknowledgement}

在我们的分析中，使用了公开数据与部分非公开数据，在此基础上采用基于净值的风格分析，基于持仓的收益归因对基金管理人的业绩表现进行了科学的分析。我们历尽所能的使用了最为完整与详实的数据、最为科学的方法，以最为严谨的态度做出尽量客观的评价。同时我们也实地进行调研与基金经理人进行了多次的交流。在此，对于向我们提供数据与交流机会的相关人员致谢。需要根伟详细的技术分析报告，请与本文作者联系。

\end{acknowledgement}



